Task 5 Update

diff --git a/0x07-networking_basics/5-is_the_host_on_the_network b/0x07-networking_basics/5-is_the_host_on_the_network
--- a/0x07-networking_basics/5-is_the_host_on_the_network
+++ b/0x07-networking_basics/5-is_the_host_on_the_network
@@ -4,28 +4,22 @@
 # Pings an IP address received as an argument 5 times.
 #
 # Usage:
-#	./ping_ip.sh {IP_ADDRESS}
+#       ./ping_ip.sh {IP_ADDRESS}
 #
 # Arguments:
-#	IP_ADDRESS: The IP address to ping.
+#       IP_ADDRESS: The IP address to ping.
 #
 # Exit Codes:
-#	0: Successful execution.
-#	1: No IP address provided.
-#	2: Ping command failed.
+#       0: Successful execution.
+#       1: No IP address provided.
+#       2: Ping command failed.
 
-if [ $# -eq 0 ]; then
-	echo "Usage: ./ping_ip.sh {IP_ADDRESS}"
-	exit 1
+# Check if an IP address is provided
+if [ $# -lt 1 ]; then
+    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
+    exit 1
 fi
 
 IP_ADDRESS=$1
 
-ping -c 5 "$IP_ADDRESS"
-if [ $? -ne 0 ]
-then
-	echo "Failed to ping $IP_ADDRESS"
-	exit 2
-fi
-
-exit 0
+ping -c 5 "$IP_ADDRESS" || exit 2
